# Generated by Django 5.1.7 on 2025-04-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Homme'), ('female', 'Femme'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Sexe')),
                ('cin', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro CIN')),
                ('role', models.CharField(choices=[('visitor', 'Visiteur'), ('service_provider', 'Fournisseur de service')], default='visitor', max_length=20, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
